# Generated by Django 4.2.16 on 2024-10-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
