# Generated by Django 4.2.16 on 2024-10-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt", "0004_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
