# Generated by Django 4.2.16 on 2024-10-15 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt", "0005_users_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="users",
        ),
        migrations.AddField(
            model_name="chat_history",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
